version: "3.8"

services:
#  cluster-base:
#    build:
#      context: ./docker
#      dockerfile: cluster-base.Dockerfile
#      args:
#        debian_buster_image_tag: 11-jre-slim
#        shared_workspace: /opt/workspace
#        spark_version: 3.2.0
#    container_name: cluster-base

  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/workspace

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8082:8081"
    volumes:
      - ./data:/opt/workspace
    depends_on:
      - spark-master

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./data:/opt/workspace

  web-app:
    image: web-app
    container_name: web-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/opt/app
      - ./data:/opt/workspace
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local