DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  comment TEXT UNIQUE NOT NULL,
  sentiment SMALLINT NOT NULL,
  created_at TIMESTAMP NOT NULL
);